name: credit_card
description: Cool Credit card widget
version: 0.1.6
author: Laxman Bhattarai <erluxman@gmail.com>
homepage: https://github.com/erluxman
issue_tracker: https://github.com/erluxman

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  cached_network_image: ^1.1.1
  

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - icons/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: halter
      fonts:
        - asset: font/halter.ttf
    - family: credit-card
      fonts:
        - asset: font/credit-card.ttf

    - family: Jannat
      fonts:
        - asset: font/jannat_regular.ttf